[general]
import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_title = true
startup_mode = "Maximized"

option_as_alt = "Both"

[window.padding]
x = 10
y = 10

[font]
size = 14

[font.normal]
family = "JetBrainsMono NFM"

[cursor.style]
blinking = "Off"
shape = "Block"

[mouse]
hide_when_typing = true
