# syntax=toml

[options]
# Enables focus follows mouse. Set to false or remove the line to disable.
focus_follows_mouse = true

# How many fingers to use for moving windows left and right.
# Values lower than 3 will be ignored.
swipe_gesture_fingers = 4

[bindings]
# Bindings run arbitrary shell via /bin/bash -lc.
# Use 'paneru cmd ...' to send Paneru commands to the daemon.

# Moves the focus between windows.
"alt - h" = "paneru cmd window focus west"
"alt - l" = "paneru cmd window focus east"
"alt - k" = "paneru cmd window focus north"
"alt - j" = "paneru cmd window focus south"

# Swaps windows in chosen direction.
"alt + shift - h" = "paneru cmd window swap west"
"alt + shift - l" = "paneru cmd window swap east"

# Jump to the left-most or right-most windows.
# "cmd + shift - h" = "paneru cmd window focus first"
# "cmd + shift - l" = "paneru cmd window focus last"

# Move the current window into the left-most or right-most positions.
# "alt + shift - h" = "paneru cmd window swap first"
# "alt + shift - l" = "paneru cmd window swap last"

# Centers the current window on screen.
"alt - c" = "paneru cmd window center"

# Shuffle window widths: 25%, 33%, 50%, 66%, 75%.
"alt - r" = "paneru cmd window resize"

# Toggle manage (floating vs managed).
"alt - f" = "paneru cmd window manage"

# Stack/Unstack window into the left column.
# "alt - ]" = "paneru cmd window stack"
# "alt + shift - ]" = "paneru cmd window unstack"

# Quit paneru.
# "ctrl + alt - q" = "paneru cmd quit"

# Example: run arbitrary shell
# "alt+h" = "echo 'hello from exec (alt+h)'"
# "cmd + shift - r" = "osascript -e 'display dialog \"paneru exec\"'"

"cmd + alt + shift + ctrl + f" = "open -a finder"
"cmd + alt + shift + ctrl + b" = "open -a firefox"
"cmd + alt + shift + ctrl + t" = "open -a \"Ghostty\""
"cmd + alt + shift + ctrl + n" = "open -a \"Notes\""
"cmd + alt + shift + ctrl + m" = "open -a \"Mail\""
"cmd + alt + shift + ctrl + c" = "open -a \"Calendar\""
"cmd + alt + shift + ctrl + w" = "open -a \"WhatsApp\""
"cmd + alt + shift + ctrl + s" = "open -a \"System Preferences\""
"cmd + alt + shift + ctrl + p" = "open -a \"Passwords\""
"cmd + alt + shift + ctrl + a" = "open -a \"Activity Monitor\""
