system: "base16"
name: "Rosé Pine Moon"
author: "Kyle <me@kylewong.my>"
slug: "rose-pine-moon"
variant: "dark"
palette:
  base00: "#232136"
  base01: "#2a273f"
  base02: "#393552"
  base03: "#6e6a86"
  base04: "#908caa"
  base05: "#e0def4"
  base06: "#e0def4"
  base07: "#56526e"
  base08: "#eb6f92"
  base09: "#ea9a97"
  base0A: "#f6c177"
  base0B: "#95b1ac"
  base0C: "#9ccfd8"
  base0D: "#3e8fb0"
  base0E: "#c4a7e7"
  base0F: "#56526e"
