[default_session]
startup_command = "nvim +\"lua Snacks.picker.files()\""
preview_command = "tree -L 1 -C --dirsfirst -a {}"

[[session]]
name = "home (~)"
path = "~"
startup_command = "ls"

[[session]]
name = "start kanata"
path = "~/nix-system-config-v2/"
startup_command = "just kanata"

[[session]]
name = "downloads"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "nix config"
path = "~/nix-system-config-v2"

[[session]]
name = "neovim config"
path = "~/nix-system-config-v2/config/nvim"

[[session]]
name = "sesh config"
path = "~/nix-system-config-v2/config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --color=always ~/nix-system-config-v2/config/sesh/sesh.toml"

[[session]]
name = "ghostty config"
path = "~/nix-system-config-v2/config/ghostty"
startup_command = "nvim config"
preview_command = "bat --color=always ~/nix-system-config-v2/config/ghostty/config"

[[session]]
name = "tmux config"
path = "~/nix-system-config-v2/home"
startup_command = "nvim multiplexer.nix"
preview_command = "bat --color=always ~/nix-system-config-v2/home/multiplexer.nix"

[[session]]
name = "aerospace config"
path = "~/nix-system-config-v2/modules/custom"
startup_command = "nvim aerospace.nix"
preview_command = "bat --color=always ~/nix-system-config-v2/modules/custom/aerospace.nix"

[[session]]
name = "btop"
path = "~"
startup_command = "btop"
