name: Mirror Subdirectory

on:
    push:
        branches:
            - main # Trigger on push to your main branch
        paths:
            - "config/nvim/**" # Trigger only if changes occur in this folder

permissions:
    contents: write

jobs:
    mirror-nvim:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Get full history for subtree splitting
                  token: ${{ secrets.PAT }}

            - name: Set up Git Config
              run: |
                  git config --global user.name "${{ github.actor }}"
                  git config --global user.email "${{ github.actor }}@users.noreply.github.com"

            - name: Create Subtree Branch
              run: |
                  git subtree split --prefix=config/nvim -b nvim-config

            - name: Add Remote and Push Subtree
              env:
                  PAT: ${{ secrets.PAT }}

              run: |
                  MIRROR_URL="https://x-access-token:${PAT}@github.com/y3owk1n/nvim.git"
                  echo "Using mirror URL: $MIRROR_URL"

                  git remote remove nvim-config || true
                  git remote add nvim-config "$MIRROR_URL"

                  unset GITHUB_TOKEN

                  git config --global --unset credential.helper || true

                  git remote -v  # For debugging: check the remote URL

                  git push nvim-config nvim-config:main --force
